name: Sync LeetCode Solutions

on:
  workflow_dispatch: # Allows manual trigger button
  schedule:
    - cron: '0 0 * * *' # Runs automatically every single day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: '.'
